// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"rmmv_MorzanBase","status":true,"description":"Base Plugin.","parameters":{}},
{"name":"rmmv_MorzanTime","status":true,"description":"Time Management.","parameters":{"VariableDay":"2","VariablePeriod":"3","NamesPeriods":"Dawn;Morning;Noon;Afternoon;Evening;Night"}},
{"name":"rmmv_MorzanProgression","status":true,"description":"Progression and stats.","parameters":{}},
{"name":"rmmv_MorzanPhoneMenu","status":true,"description":"Plugin displaying a phone menu","parameters":{"Delay":"","Text Log Button":"","Send Text Button":"","Hint Button":"","Cancel Button":"","Phone Image":"","Phone Horizontal Padding":"","Phone Vertical Padding":""}},
{"name":"rmmv_MorzanScene","status":true,"description":"Generate a cutscene based on a txt file.","parameters":{"Scenes Folder":"","Scenes Images Folder":"","Background Folder":"","Background Extension":""}}
];
